// Code auto-generated by MessageBrokerGenerator
// Re-run the generator every time a new RequestMessage is added or removed.

using UnityEngine;
using UnityEditor;

namespace Assets.Scripts.MessageBroker
{
	public partial class MessageBroker
	{
		public object Send_RequestMessage2(RequestMessagePayload payload)
		{
			if (payload == null)
			{
				Debug.LogWarning("Payload is null.");
				return null;
			}
			m_RequestMessage2.SendMessage(payload);

			return payload.payload;
		}
	}
}
