// Code auto-generated by MessageBrokerGenerator

using UnityEngine;
using UnityEditor;

namespace Assets.Scripts.MessageBroker
{
	public partial class MessageBroker : MonoBehaviour
	{
		private RequestMessage m_RequestMessage1;
		private RequestMessage m_RequestMessage2;
		void Start()
		{
			this.m_RequestMessage1 = AssetDatabase.LoadAssetAtPath<RequestMessage>("Assets/Prefabs/MessageBroker/RequestMessage1.asset");
			this.m_RequestMessage2 = AssetDatabase.LoadAssetAtPath<RequestMessage>("Assets/Prefabs/MessageBroker/RequestMessage2.asset");
		}
	}
}
