// Code auto-generated by MessageBrokerGenerator
// Re-run the generator every time a new Message is added or removed.

using UnityEngine;
using UnityEditor;

namespace Assets.Scripts.MessageBroker
{
	public static partial class MessageBroker
	{
		public static MBPlayer Player = new MBPlayer();
	}
	public class MBPlayer
	{
		private Message m_RequestMessage1;
		public MBPlayer()
		{
			this.m_RequestMessage1 = AssetDatabase.LoadAssetAtPath<Message>("Assets/Prefabs/MessageBroker/RequestMessage1.asset");
		}
		public object Send_RequestMessage1(MessagePayload payload)
		{
			if (payload == null)
			{
				Debug.LogWarning("Payload is null.");
				return null;
			}
			m_RequestMessage1.SendMessage(payload);

			return payload.payload;
		}
	}
}
