// Code auto-generated by MessageBrokerGenerator
// Re-run the generator every time a new Message is added or removed.

using UnityEngine;
using UnityEditor;

namespace Assets.Scripts.MessageBroker
{
	public static partial class MessageBroker
	{
		public static MBDefault Default = new MBDefault();
	}
	public class MBDefault
	{
		private Message m_RequestMessage2;
		public MBDefault()
		{
			this.m_RequestMessage2 = AssetDatabase.LoadAssetAtPath<Message>("Assets/Prefabs/MessageBroker/RequestMessage2.asset");
		}
		public object Send_RequestMessage2(MessagePayload payload)
		{
			if (payload == null)
			{
				Debug.LogWarning("Payload is null.");
				return null;
			}
			m_RequestMessage2.SendMessage(payload);

			return payload.payload;
		}
	}
}
