//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InFlammis.MessageBroker
{
	/// <summary>
	/// Interface for the Message Broker component.
	/// </summary>
	interface IMessageBroker
	{
		/// <summary>
		/// Message Broker for `App` category
		/// </summary>
		MBApp App { get; }

		/// <summary>
		/// Message Broker for `Digigram` category
		/// </summary>
		MBDigigram Digigram { get; }

		/// <summary>
		/// Message Broker for `Interaction` category
		/// </summary>
		MBInteraction Interaction { get; }

		/// <summary>
		/// Message Broker for `Render` category
		/// </summary>
		MBRender Render { get; }

	}
}
