//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator version 1.0.0-alpha.1.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;

namespace InFlammis.MessageBroker
{
	/// <summary>
	/// MessageBroker publisher for App category.
	/// </summary>
	class MBApp
	{
		#region Event declaration

		/// <summary>
		/// 
		/// </summary>
		public event Action<object, object> Shutdown;

		/// <summary>
		/// 
		/// </summary>
		public event Action<object, object> Startup;


		#endregion

		#region Send methods

		/// <summary>
		/// Send a message of type Shutdown.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// </summary>
		public void Send_Shutdown(object sender, object target)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return;
			}

			Shutdown?.Invoke(sender, target);
		}

		/// <summary>
		/// Send a message of type Startup.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// </summary>
		public void Send_Startup(object sender, object target)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return;
			}

			Startup?.Invoke(sender, target);
		}


		#endregion

	}
}
