//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator version 1.0.0-alpha.1.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;

namespace InFlammis.MessageBroker
{
	/// <summary>
	/// MessageBroker publisher for Digigram category.
	/// </summary>
	class MBDigigram
	{
		#region Event declaration

		/// <summary>
		/// Message to request the Digigram size
		/// </summary>
		public event Func<object, object, UnityEngine.Vector2Int?> RequestForSize;


		#endregion

		#region Send methods

		/// <summary>
		/// Send a message of type RequestForSize.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// <returns>The digigram size</returns>
		/// </summary>
		public UnityEngine.Vector2Int? Send_RequestForSize(object sender, object target)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return default;
			}

			return RequestForSize?.Invoke(sender, target);
		}


		#endregion

	}
}
