//------------------------------------------------------------------------------
// <auto-generated>
// Code auto-generated by MessageBrokerGenerator version 1.0.0-alpha.1.
// Re-run the generator every time a new Message is added or removed.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEditor;

namespace InFlammis.MessageBroker
{
	/// <summary>
	/// MessageBroker publisher for Render category.
	/// </summary>
	class MBRender
	{
		#region Event declaration

		/// <summary>
		/// Message notifying that the main texture has been updated.
		/// </summary>
		public event Action<object, object, UnityEngine.RenderTexture> TextureUpdated;


		#endregion

		#region Send methods

		/// <summary>
		/// Send a message of type TextureUpdated.
		/// <param name="sender">The sender of the message. Required.</param>
		/// <param name="target">The target of the message. Optional.</param>
		/// <param name="texture">The new texture rendered.</param>
		/// </summary>
		public void Send_TextureUpdated(object sender, object target, UnityEngine.RenderTexture texture)
		{
			if (sender == null)
			{
				Debug.LogError("sender is required.");
				return;
			}

			TextureUpdated?.Invoke(sender, target, texture);
		}


		#endregion

	}
}
